ALTER TABLE "wms_invoice_lines"
ADD COLUMN "itemSubtext" TEXT,
ADD COLUMN "vatEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "vatRate" DECIMAL(5, 2) NOT NULL DEFAULT 0,
ADD COLUMN "vatAmount" DECIMAL(14, 2) NOT NULL DEFAULT 0;
