ALTER TYPE "WmsBasketStatus" ADD VALUE IF NOT EXISTS 'AVAILABLE';
ALTER TYPE "WmsBasketStatus" ADD VALUE IF NOT EXISTS 'PACKING';
ALTER TYPE "WmsBasketStatus" ADD VALUE IF NOT EXISTS 'DAMAGED';
ALTER TYPE "WmsBasketStatus" ADD VALUE IF NOT EXISTS 'RETIRED';
