ALTER TYPE "WmsPurchasingBatchStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PRODUCTS';
ALTER TYPE "WmsPurchasingBatchStatus" ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE "WmsPurchasingBatchStatus" ADD VALUE IF NOT EXISTS 'RECEIVING_EXCEPTION';
